# Use an official Node.js image (version 18) as the build environment
FROM python:3

WORKDIR /app/

# Set the working directory

# Copy the rest of the application code
COPY Testbed-Tutorial .

RUN pip install mkdocs==1.6.0 mkdocs-material==9.5.21 mkdocs-static-i18n==1.2.3

COPY tutorial-build-entrypoint.sh .
